### ISSUE TITLE
#Warning# Folder name changes

### ISSUE THREAD

**Issue by ulklc** [ulklc/covid19-timeseries#6]
I'll update `report` folder name to `countryReport` on next automated report generation (2020/03/25 00:00 GMT 0). I have a plan to add state level data after understand to possibility. If we can, it will be under the `stateReport`.

Thanks

**Comment by kgiannakelos** [comment]
@ulklc Hello! 

Thanks for your hard work but could you please not rename this folder since we will need to change the url for downloading? You could add an additional folder under country or report folders to add the state level data without breaking any existing integration with your data downloads.

Thanks once more.

**Comment by chrisjbillington** [comment]
Johns Hopkins insisting on not changing old files and always introducing new ones with inconsistent conventions was the source of much of the difficulty of using their dataset - I think when it becomes apparent that something should be renamed, it should simply be renamed. If you want the old one, that's what version control is for. You can use an old version.

Better to do the renaming now before too many people are using the dataset. In the long run one should be careful to not rename things too often, but given this repository has existed for less than a day I think it's fair to let it find its feet before expecting backward compatibility.

**Comment by kgiannakelos** [comment]
@chrisjbillington I agree with you that this is a new repository but this rename does not provide any benefit to the organization of the reports. It's more preferable to have entities organized like this /report/country/state rather than /countryReport  /stateReport since it provides a better hierrarchy. Otherwise more renames will occur.

**Comment by ulklc** [comment]
As chris said. before more users activity, I have to decide folder structure for backward compatibility. State reports will be seperate pipe from country. and currently structure plan is looking like:

Country data ISO Code based `countryReport/country/{countryCode}.csv`
Country data daily basis `countryReport/daily/{YYYY-MM-DD}.csv`
Country data raw `countryReport/raw/raw.csv`

State data
State data ISO Code based `stateReport/state/{state/province code}.csv`
State data daily basis `stateReport/daily/{YYYY-MM-DD}.csv`
State data raw `stateReport/raw/raw.csv`

If we needs other types like region, we can add new folder instead of managing subfolders.

Also after this changes, I'll not touch country and state folder structure (if we really really have to, we can discuss in future)

**Comment by ulklc** [comment]
Changes deployed

**Comment by iandoug** [comment]
Please put these sort of announcements on the homepage readme, rather than buried in a closed issue.
